#Network Policy to Isolate dynamic-enablement pod. Given least privliged access and can only communicate with other pods in it's namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dyn-policy
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      group: blue
  policyTypes:
    - Egress
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: {{ .Values.namespace }}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53