name: 'Terraform EKS'

on:
  push:
    branches: main
    paths: [ terraform/resources/** ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform
      - name: Set Context
        env:
          access_key: ${{ secret.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
        run: |
          aws --version
          aws configure set aws_access_key_id $access_key
          aws configure set aws_secret_access_key $secret_key
          aws configure set region us-east-2
          aws configure set output json
          aws eks --region $region update-kubeconfig --name $cluster_name
          kubectl get svc
          cat ~/.kube/config

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: AWS_PROFILE=729347766675 AWS_REGION=us-east-2 terraform init ./terraform/resources/dynamic-enablement/eks-node-group

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run:  AWS_PROFILE=729347766675 AWS_REGION=us-east-2 terraform plan ./terraform/resources/dynamic-enablement/eks-node-group

        # On push to main, build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run:  AWS_PROFILE=729347766675 AWS_REGION=us-east-2 terraform apply ./terraform/resources/dynamic-enablement/eks-node-group -auto-approve

